/**
 * English baseline copy — the reference every other language mirrors.
 * Migrated verbatim from the old `vocab.ts` so behaviour is unchanged.
 */
import { makeStatus, type Vocab } from "./types";

export const en: Vocab = {
  langName: "English",
  tagline: "Bitcoin inheritance, without the lawyers.",
  longTagline:
    "Set up once. Tap once a month to say you're here. If you ever stop, the people you chose can claim what's theirs.",
  status: makeStatus({
    unfunded: {
      label: "Awaiting funding",
      long: "Send Bitcoin to your vault to activate it. Check-ins start once it's funded.",
    },
    ok: {
      label: "Active",
      long: "Everything is in order.",
    },
    warning: {
      label: "Tap soon",
      long: "A reminder is coming up. Tap when you can.",
    },
    alarmed: {
      label: "Reminder missed",
      long: "Tap now to reset the clock. Nothing is lost yet.",
    },
    timelock_started: {
      label: "Claim issued",
      long: "Your heir was sent the claim link.",
    },
    claiming: {
      label: "Claiming",
      long: "Your heir is broadcasting the claim transaction.",
    },
    claimed: {
      label: "Passed on",
      long: "This vault has been claimed.",
    },
    frozen: {
      label: "Panic stop",
      long: "You triggered a panic. The vault is frozen for 90 days.",
    },
  }),
  claim: {
    header: "A message for you",
    loading: "Opening your link…",
    notFound: {
      eyebrow: "This link doesn't work",
      title: "We couldn't find anything for this link",
      body: "The link may be incomplete, expired, or copied wrong. If someone gave you this by SMS or WhatsApp, ask them to send it again from the start.",
    },
    alreadyUsed: {
      eyebrow: "This link has already been opened",
      title: "Looks like someone has been here before",
      body: "A claim link works once. If you've already received what was left for you, you're done. If you haven't, contact the person who set this up. They can issue a new link.",
    },
    timelockWait: {
      eyebrow: "Your inheritance",
      title: "Your funds are on the way",
      etaBefore: "What was left for you unlocks on the Bitcoin network around ",
      etaAfter:
        ". There's nothing for you to do. We'll email you when it's ready, and you can come back using this same link.",
      noEta:
        "We're still confirming the funds on the Bitcoin network. There's nothing for you to do. Check back shortly using this same link.",
      note: "Bitcoin holds an inheritance for a set time before it can be collected.",
    },
    safetyWait: {
      eyebrow: "Almost there",
      title: "Your claim has started. There's a short safety wait",
      body1:
        "You've done everything right, and what was left for you is being prepared. For everyone's protection, every claim includes a short waiting period before anything can be collected.",
      body2Before:
        "We'll email you the moment everything's ready, so you don't have to remember or keep checking. You can also come back ",
      body2After: " using this same link.",
      note: "Why the wait? It gives the person who set this up one last chance to respond if this claim was started by mistake. If nothing changes, your claim continues automatically.",
    },
    notReady: {
      eyebrow: "Not yet",
      title: "It's not time yet",
      body: "The person who set this up is still active. There's nothing for you to do today. You'll receive a new message if anything changes.",
      nextCheckin: (friendly) => `Next check-in ${friendly}.`,
    },
    alreadyClaimed: {
      eyebrow: "Done",
      title: "This has already been passed on",
      body: (label) =>
        `${
          label ? `"${label}" was claimed earlier.` : "This inheritance was claimed earlier."
        } Nothing more to do here.`,
    },
    error: {
      eyebrow: "Something went wrong",
      tryAgain: "Try again",
    },
    checking: {
      eyebrow: "One moment",
      title: "We're checking the Bitcoin network",
      body: "This is taking a moment. Leave this page open, or come back using the same link in a little while.",
      firstLoadSlow: "This can take up to a minute the first time. You can leave this page open and it will update on its own.",
      firstLoadEstimating: "Checking when your funds are ready…",
    },
    probeError: {
      holdOn: "Hold on",
    },
    technical: {
      showDetails: "Show technical details",
    },
    footer: "This page is from GhostKey, a Bitcoin inheritance service. The link you opened was sent to you because someone you knew set up an inheritance and named your phone or email.",
  },
  drill: {
    bannerTitle: "This is a practice run",
    bannerBody: "Everyone is fine, and nothing real happens on this page. It exists so the real thing is not the first time you see it.",
    introEyebrow: "A practice run",
    introTitle: (name) =>
      name ? `Hello ${name}, someone set something aside for you` : "Hello, someone set something aside for you",
    introBody1: "They use GhostKey to make sure that if they ever stopped being around, what they saved in Bitcoin would reach you. They asked us to show you how that works, today, while they can answer your questions.",
    introBody2: "It takes about a minute. You don't need an account and you can't break anything.",
    introCta: "Show me how it works",
    walkthroughEyebrow: "What the real day looks like",
    walkthroughTitle: "Three things happen",
    walkthroughStep1Title: "1. You get a message like today's",
    walkthroughStep1Body: "If they stop confirming they're okay, we send you a link, just like the one you opened. That part you've already practiced.",
    walkthroughStep2Title: "2. There's a short wait",
    walkthroughStep2Body: "Bitcoin itself enforces a waiting period, and this page shows you the date. You just come back when it says to. If they recorded a video message for you, it plays here on the real day.",
    walkthroughStep3Title: "3. The money comes straight to you",
    walkthroughStep3Body: "You paste an address from any Bitcoin wallet on your phone, and it arrives there. GhostKey never holds the money, so there's no company that can lose it or keep it from you.",
    walkthroughFinishing: "Finishing…",
    walkthroughFinish: "Finish the practice",
    doneEyebrow: "Practice complete",
    doneTitle: "You're done, and you did it right",
    doneBody: "The person who set this up will see that the practice worked. Nothing moved and nothing changed. If the real day ever comes, it will look exactly like what you just walked through.",
    doneClose: "You can close this page.",
  },
  claimCommon: {
    whatIsBeingPassedOn: "What's being passed on",
    defaultLabel: "A Bitcoin inheritance",
    step1: "Step 1",
    step2: "Step 2",
    step3: "Step 3",
    whereShouldMoneyGo: "Where should the money go?",
    bitcoinAddress: "Your Bitcoin address",
    reviewAndSend: "Review and send",
    sendingBitcoin: "Sending Bitcoin…",
    sendTheBitcoin: "Send the Bitcoin",
    everythingMinusFee: "Everything in the vault, minus the network fee",
    defaultFeeLabel: "2 sat/vB",
    someonesLeftYou: "Someone left you something",
    pageDescription: "Someone you knew left you Bitcoin. They set up GhostKey so that if they ever stopped checking in, the link would reach you. That's what happened. This page is for you.",
    advancedFee: "Advanced: change the network fee",
    feeRateLabel: "Fee rate in sat/vB (optional)",
    feeRateInvalid: "Enter a whole number between 1 and 1000, or leave blank.",
    feeRateHint: "Leave blank to use 2 sat/vB.",
    feeRateHintDetailed: "Leave blank to use 2 sat/vB. Raise it if you need the transaction to confirm faster.",
    addressInvalidShape: "That doesn't look like a Bitcoin address. Check the start.",
    doYouHaveWallet: "Do you have a Bitcoin wallet?",
    walletDesc: (network, examples) =>
      `A Bitcoin wallet is an app where you can receive Bitcoin. You only need one that can receive on the ${network}. A Lightning wallet works too. ${examples} all work.`,
    haveWalletYes: "Yes, I do",
    haveWalletYesSub: "Skip to step 2",
    haveWalletNo: "No, not yet",
    haveWalletNoSub: "We'll point you somewhere",
    onNetwork: (network) => `On the ${network}.`,
    addressInstructions1: "Open any Bitcoin wallet and tap ",
    addressInstructions2: " to get an address. Copy the long address that starts with ",
    addressInstructions3: " and paste it below.",
    addressWrongNetwork: (prefix) =>
      `That address is for a different network. It should start with ${prefix}.`,
    addressPlaceholder: (prefix) => `${prefix}...`,
    confirmDescription: "We'll show you the details to check, then prepare and broadcast the transaction for you. You don't need to sign anything in another app.",
  },
  guardian: {
    sentEyebrow: "It's done",
    sentTitle: "Sent.",
    eyebrow: "Two of you, together",
    greeting: (heir, isHeir) => isHeir ? `Hello ${heir}.` : `Helping ${heir}.`,
    heirBody: (heir) =>
      `Someone set this up so that ${heir} and a trusted guardian finish it together. You can't do it alone, and that's on purpose. Ask one guardian to be with you now.`,
    guardianBody: (heir) =>
      `${heir} was set up with a guardian's help. You're one of the guardians. To finish, ${heir} and you do this together on this page.`,
    bringLink: (needLabel) => `Bring in ${needLabel} link`,
    heirLinkInstructions: "Each guardian got their own message with a link. Ask one guardian to open their link and paste it below, or paste it for them.",
    guardianLinkInstructions: "The heir got their own message with a link. Paste it below so the two halves come together.",
    bothLinksReady: "Both links are here. You can finish below.",
    pasteLink: (needLabel) => `Paste ${needLabel} link`,
    linkHint: "It's the long web link from their message.",
    checking: "Checking…",
    addLink: "Add this link",
    confirmDescription: "We'll show you the details to check, then prepare and broadcast the transaction for both of you. No app to install.",
    errInvalidLink: "That doesn't look like a GhostKey link. Paste the whole link.",
    errSameLink: "That's the link you already opened. Paste the other person's link.",
    errDifferentVault: "That link is for a different inheritance. Check you have the right one.",
    errWrongRoleHeir: "That's another heir link. You need a guardian's link to finish.",
    errWrongRoleGuardian: "That's a guardian link. You need the heir's link to finish.",
    errAlreadyUsed: "That link has already been used.",
    errCheckFailed: "We couldn't check that link. Try again in a moment.",
  },
  derivedClaim: {
    confirmEmail: (email) => `They told us to expect ${email}.`,
    stopAndContact: "If that's not your email, stop and reach out to whoever sent you this link.",
    whereShouldMoneyGo: (network, examples) =>
      `Paste any Bitcoin address you control on the ${network}. A Lightning wallet works too. Apps like Blink, Bitnob, or Wallet of Satoshi each give you a Bitcoin address that adds the money to your balance. ${examples}.`,
    reviewAndClaim: "Review and claim",
    claimingAndSending: "Sending Bitcoin…",
    claimAndSend: "Claim and send",
    advancedFee: "Advanced: custom fee rate",
    feePlaceholder: "sat/vB (optional, e.g. 4)",
    yourBackupPhrase: "Your backup phrase",
    backupDescription: "Write these 12 words down somewhere safe. They're the only way to recover this key without GhostKey. The funds you just claimed are already on their way to your address. This is just insurance.",
  },
  manualClaim: {
    walletDesc: (network) =>
      `A Bitcoin wallet is an app where you can receive and hold Bitcoin on the ${network}. This claim is special: it needs a wallet that can sign a Bitcoin Taproot timelock. Most phone wallets can't. The one we've tested is Bitcoin Core, on a computer.`,
    walletWarning: "One thing to check first: most phone wallets can't sign this kind of claim. If your wallet can't sign a Bitcoin Taproot script, choose No, not yet and we'll point you to Bitcoin Core.",
    bitcoinAddress: "Your Bitcoin address",
    whereShouldBitcoinGo: "Where should the Bitcoin go?",
    prepareTransaction: "Prepare transaction",
    preparingTransaction: "Preparing transaction…",
    signInWallet: "Sign it in your wallet",
    signInstructions: "We've prepared an unsigned transaction. GhostKey can't sign it for you. This claim spends a Bitcoin timelock, so it needs a wallet that can sign Taproot scripts. Many phone wallets can't. Bitcoin Core is the one we've tested. If the wallet that holds your key can open and sign this, that works too. Sign it there, then paste the signed transaction back.",
    unsignedTransaction: "Unsigned transaction",
    unsignedDescription: "This long block of letters and numbers is just your transaction written out as text (its technical name is a \"PSBT\"). Nothing here can spend your money on its own. It still has to be signed. It's safe to copy.",
    copy: "Copy",
    copied: "Copied",
    signHint: "Open the wallet that holds your key, find its transaction signer (sometimes called \"sign PSBT\"), paste this in, and sign.",
    signedTransaction: "Signed transaction",
    signedHint: "Paste back what your wallet gives you after signing.",
    broadcastTransaction: "Broadcast transaction",
    broadcasting: "Broadcasting…",
    walletGuidePickAny: "Pick any of these. Download it on your phone, open it, and follow the steps inside.",
    walletPsbtDescription: "Signing this claim needs a wallet that can sign Bitcoin Taproot timelock scripts. Most phone wallets can't. The one we've tested is Bitcoin Core, on a desktop computer.",
    downloadBitcoinCore: "Download Bitcoin Core",
    walletPsbtHint: "Open the transaction below in Bitcoin Core, sign it, and paste the signed version back here.",
    psbtSummary: "Transaction summary",
    amountBeingMoved: "Amount being moved",
    youllReceive: "You'll receive",
    networkFee: "Network fee",
    networkLabel: "Network",
    psbtWarning: "Double-check these numbers in your wallet before signing. If the amount or destination looks wrong, don't sign. Come back and start again.",
  },
  broadcastSuccess: {
    done: "Done",
    itsOnTheNetwork: "It's on the network",
    description: "Your transaction has been broadcast. Bitcoin transactions usually confirm within an hour, sometimes faster. Once it's confirmed, the funds are yours.",
    transactionId: "Transaction ID",
    watchItArrive: "Watch it arrive \u2197",
    noNeedToKeepOpen: "You don't need to keep this page open. The transaction is on the Bitcoin network and will confirm on its own.",
  },
  heirRecoveryFile: {
    advanced: "Advanced: save your own recovery file",
    description: "This downloads a file that can reach this Bitcoin without GhostKey, using just a code we'll show you. You don't need it to receive the money above. It's a backup, and a way to do it yourself if you ever want to.",
    createFile: "Create my recovery file",
    preparing: "Preparing your file… this takes a few seconds.",
    couldNotBuild: (message) => `Couldn't build the file: ${message}`,
    tryAgain: "Try again",
    yourCode: "Your code, write it down",
    codeDescription: "The file is locked with this code. We won't show it again, and we never store it. Keep the file and the code together.",
    downloadFile: "Download the file",
  },
  claimErrors: {
    destinationMismatch: {
      headline: "That address doesn't fit",
      body: "The address you pasted doesn't match the network this Bitcoin is on. They look similar but start with different letters.",
      nextStep: "Open your wallet, make sure it's on the right network, and copy a fresh address.",
    },
    noUtxos: {
      headline: "There's nothing to claim yet",
      body: "The vault is empty right now. Either it hasn't been funded, or someone has already moved the Bitcoin out.",
      nextStep: "Contact the person who set this up. They can tell you whether to wait or whether nothing was ever inside.",
    },
    psbtNotFullySigned: {
      headline: "Your signature isn't complete",
      body: "The pre-signed transaction came back without all the signatures it needs.",
      nextStep: "Open the transaction in your wallet again, finish signing, and paste the new result back here.",
    },
    timelockNotMatured: {
      headline: "The waiting period isn't over",
      body: "Bitcoin enforces a delay between when the alarm fired and when the funds can be moved. The clock runs on the chain, not on this server.",
      nextStep: "Come back to this page in a few hours. Your link is still valid.",
    },
    esploraDown: {
      headline: "We can't reach the Bitcoin network right now",
      body: "Our connection to the public Bitcoin index is down. This is a temporary outage on our side.",
      nextStep: "Try again in a few minutes. Your link is still valid.",
    },
    olderFormat: {
      headline: "This link uses an older format",
      body: "The way this vault was set up is supported, but our automatic detection got confused.",
      nextStep: "Contact the person who set this up so we can help finish the claim by hand.",
    },
    serverError: {
      headline: "Something went wrong on our end",
      body: "This isn't something you can fix from your side, and your link is still valid.",
      nextStep: "Try again in a few minutes. If it keeps happening, contact the person who set this up.",
    },
    linkIncomplete: {
      headline: "Your link looks incomplete",
      body: "Part of this link carries the key needed to unlock the inheritance. The link we received isn't whole, usually because it got cut off when it was shared.",
      nextStep: "Ask the person who sent it to share the full link again.",
    },
    genericResolve: {
      headline: "We couldn't open your link",
      body: "Something went wrong loading the page. This isn't anything you did.",
      nextStep: "Try again in a moment. If it keeps happening, ask the sender to re-share the link.",
    },
    genericProbe: {
      headline: "We hit a snag opening your link",
      body: "We couldn't read the details for this inheritance.",
      nextStep: "Try again in a moment. If it keeps happening, contact the person who set this up.",
    },
    genericSend: {
      headline: "We couldn't complete the transfer",
      body: "Something went wrong sending the Bitcoin. The transfer didn't go through, and your link is still valid.",
      nextStep: "Try again in a few minutes. If it keeps happening, contact the person who set this up.",
    },
    genericBuild: {
      headline: "We couldn't prepare the transaction",
      body: "Something went wrong putting the transaction together. Your link is still valid.",
      nextStep: "Try again in a few minutes. If it keeps happening, contact the person who set this up.",
    },
    genericBroadcast: {
      headline: "We couldn't send the transaction",
      body: "Something went wrong publishing the signed transaction. Your link is still valid and the funds haven't moved.",
      nextStep: "Open the transaction in your wallet again, sign it cleanly, and paste the result back here.",
    },
  },
  inheritPortal: {
    eyebrow: "Inherit",
    title: "Someone trusted you with this",
    description: "If you're here, someone you knew left something behind and trusted you to look after it. We'll walk you through it slowly, one step at a time. If you don't have your link yet, that's normal. It arrives by SMS, WhatsApp, or email when the time comes. There's no account to sign in to.",
    whatLinkLooksLike: "What the link looks like",
    linkExample: "https://www.ghostkeyapp.com/#/claim/AbCdEf12_3456_etc…",
    linkPrivacyNote: "Your link is private and works only once. Please don't share it with anyone.",
    alreadyHaveLink: "Already have your link?",
    linkHint: "Paste the whole link, or just the code at the end.",
    linkPlaceholder: "https://www.ghostkeyapp.com/#/claim/…",
    openIt: "Open it",
    noLinkYet: "Don't have a link yet? That's normal. You'll only receive one if the person who set up the vault stops checking in. Until then, there is nothing on this site for you to do.",
  },
  practiceCard: {
    title: "Practice claim",
    realClaimLooksSame: "The real claim will look exactly like what they practiced.",
    sendAgain: "Send again",
    sendPractice: "Send a practice",
    cancel: "Cancel",
    sending: "Sending…",
    errorRealClaimUnderway: "A real claim is already underway on this vault, so a practice run isn't possible.",
    errorSendingFailed: "Sending failed. Your vault is fine. Try again in a moment.",
    lineCompleted: (who, when) =>
      when ? `${who} completed a practice claim on ${when}.` : `${who} completed a practice claim.`,
    lineOpened: (who, when) =>
      when
        ? `${who} opened the practice link on ${when} but hasn't finished it.`
        : `${who} opened the practice link but hasn't finished it.`,
    lineSent: (who, when) =>
      when
        ? `Practice sent ${when}. ${who} hasn't opened it yet.`
        : `Practice sent. ${who} hasn't opened it yet.`,
    lineIdle: (who, noun) =>
      `See the claim work while you're here to help. ${who} gets a clearly-marked ${noun} and walks the real steps. Nothing can move.`,
    confirmAlert: (alert) => `${alert} The message says clearly that you are fine and that this is practice.`,
    sentNotified: (who) => `On its way. You'll see it here when ${who} opens the link and when they finish.`,
    sentNotNotified: (who) => `We couldn't reach ${who} automatically. Share this practice link with them yourself:`,
    practiceNounEmail: "practice email",
    practiceNounSms: "practice text message",
    practiceNounWhatsapp: "practice WhatsApp message",
    practiceNounDefault: "practice message",
    sendWordsEmailAlert: (who) => `This emails ${who} right now.`,
    sendWordsEmailButton: (who) => `Email ${who} now`,
    sendWordsSmsAlert: (who) => `This texts ${who} right now.`,
    sendWordsSmsButton: (who) => `Text ${who} now`,
    sendWordsWhatsappAlert: (who) => `This sends ${who} a WhatsApp message right now.`,
    sendWordsWhatsappButton: (who) => `Message ${who} on WhatsApp`,
    sendWordsDefaultAlert: (who) => `This sends ${who} a message right now.`,
    sendWordsDefaultButton: (who) => `Send it to ${who} now`,
  },
};
